import React, { useState } from 'react';
import { View, Text, StyleSheet, TouchableOpacity, ScrollView, ActivityIndicator } from 'react-native';

import { acknowledgeDisclaimer } from '../lib/disclaimer';

export default function DisclaimerScreen({ onAcknowledge }) {
  const [saving, setSaving] = useState(false);

  const handleAcknowledge = async () => {
    setSaving(true);
    try {
      await acknowledgeDisclaimer();
    } finally {
      onAcknowledge();
    }
  };

  return (
    <View style={styles.container}>
      <ScrollView contentContainerStyle={styles.content}>
        <Text style={styles.title}>Before you start</Text>

        <Text style={styles.paragraph}>
          Safe Loop Run generates running and walking loops back to your
          starting point, and — where UK crime data is available — routes
          away from recently reported hotspots.
        </Text>

        <Text style={styles.heading}>This app is not a safety guarantee</Text>
        <Text style={styles.paragraph}>
          Routes are based on historical, publicly reported crime data. That
          data is incomplete, doesn't reflect time of day, and can be weeks
          out of date. No route generated by this app is guaranteed safe.
          Always stay aware of your surroundings and use your own judgment.
        </Text>

        <Text style={styles.heading}>Location and GPS</Text>
        <Text style={styles.paragraph}>
          This app uses your device's GPS to build routes from where you are
          and to track your progress during a run. Location accuracy varies,
          especially indoors or in dense urban areas.
        </Text>

        <Text style={styles.heading}>Coverage</Text>
        <Text style={styles.paragraph}>
          Crime-aware routing only works in England, Wales, and Northern
          Ireland, where data.police.uk provides coverage. Elsewhere, you'll
          get a standard loop with no safety weighting.
        </Text>
      </ScrollView>

      <TouchableOpacity style={styles.ackBtn} onPress={handleAcknowledge} disabled={saving}>
        {saving ? <ActivityIndicator color="#fff" /> : <Text style={styles.ackBtnText}>I Understand</Text>}
      </TouchableOpacity>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#fff' },
  content: { padding: 24, paddingTop: 60, paddingBottom: 16 },
  title: { fontSize: 24, fontWeight: '700', marginBottom: 16 },
  heading: { fontSize: 15, fontWeight: '700', marginTop: 16, marginBottom: 4 },
  paragraph: { fontSize: 14, color: '#333', lineHeight: 20 },
  ackBtn: {
    backgroundColor: '#222',
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
    marginHorizontal: 24,
    marginBottom: 32,
  },
  ackBtnText: { color: '#fff', fontWeight: '700', fontSize: 16 },
});
